### ISSUE TITLE
Faucet fails from `replacement transaction underpriced`

### ISSUE THREAD

**Issue by slinlee** [Bschuster3434/fweb3_holder_matic_faucet#23]
@archae0pteryx is going to increase the price to avoid this issue.

```{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32000,
    "message": "replacement transaction underpriced"
  },
  "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"replacement transaction underpriced\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:96535)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:94078)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:94688)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:71407)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:72439\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:302489\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:96535)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:94078)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:94688)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:71407)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:72439\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:302489",
  "transaction": {
    "type": 2,
    "chainId": 137,
    "nonce": 32,
    "maxPriorityFeePerGas": {
      "type": "BigNumber",
      "hex": "0x9502f900"
    },
    "maxFeePerGas": {
      "type": "BigNumber",
      "hex": "0x03da189cbe"
    },
    "gasPrice": null,
    "gasLimit": {
      "type": "BigNumber",
      "hex": "0xe77c"
    },
    "to": "0x67806adca0fD8825DA9cddc69b9bA8837A64874b",
    "value": {
      "type": "BigNumber",
      "hex": "0x00"
    },
    "data": "0xb86d1d630000000000000000000000001a8912a243c2b70204f607f6cc20b94543664c30",
    "accessList": [],
    "hash": "0xd5a8c3e90d98430931032028296ac192fb01f57dd0dec545b3191945c19ef922",
    "v": 1,
    "r": "0xdcc45b005b0bfa9090e06e84b7543a005c7bf3df2a33707c93a67f1447346c57",
    "s": "0x68b0ff16bc060850fc3bdd07a5b8cdc2628a4c1251a1c72c71ac28d9a875224a",
    "from": "0xFCe88B6242728377F59122F3bAB325151e9133Df",
    "confirmations": 0
  },
  "transactionHash": "0xd5a8c3e90d98430931032028296ac192fb01f57dd0dec545b3191945c19ef922"
}```

**Comment by slinlee** [comment]
This was resolved with [785ee10](https://github.com/Bschuster3434/fweb3_holder_matic_faucet/commit/785ee10b1492055671f8c1f39906818f2b04c0e6) . Thanks, @Bschuster3434
